# Generated by Django 3.1.4 on 2020-12-06 01:40

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=testapp.models.get_file_path)),
                ('Created_By', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
