# Generated by Django 3.1.4 on 2020-12-06 02:34

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=testapp.models.get_file_path),
        ),
    ]
